repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]
  - repo: local
    hooks:
      - id: test
        name: test
        entry: rye run pytest
        language: system
        types: [python]
        pass_filenames: false
      - id: commit-msg
        name: conventional-commit-messages
        language: pygrep
        entry: "^(chore|test|feat|fix|build|docs|refactor)!?: ((?!.*(ing))(?!.*(ed))).*$"
        args: [--multiline, --negate] # fails if the entry is NOT matched
        stages: [commit-msg]
