repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.5.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--check]
  - repo: local
    hooks:
      - id: test
        name: test
        entry: rye run pytest
        language: system
        types: [python]
        pass_filenames: false
