[tool.poetry]
name = "scratch"
version = "0.1.0"
description = "ML from scratch"
authors = ["Nick <46641379+walln@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jaxlib =[
    { extras = ["cuda12_cudnn89"], version = "^0.4.21", markers = "platform_system == 'Linux'" },
    { version = "^0.4.21", platform = "darwin" }
]
jax = [
    { extras = ["cuda12_pip"], version = "^0.4.21", markers = "platform_system == 'Linux'" },
    { version = "^0.4.21", platform = "darwin" }    
]
flax = "^0.7.5"
loguru = "^0.7.2"
matplotlib = "^3.8.2"
scikit-learn = "^1.3.2"
numpy = "^1.26.2"
jax-dataloader = "^0.0.5"
datasets = "^2.15.0"
optax = "^0.1.7"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.7"
pytest = "^7.4.3"
pre-commit = "^3.5.0"

# [tool.poetry.group.metal]
# optional = true

# [tool.poetry.group.metal.dependencies]
# Currently jax-metal only supports jaxlib 0.4.11 - wait for update to support Metal acceleration
# jax-metal = { version = "^0.0.4", platform = "darwin" }

[[tool.poetry.source]]
name = "jorenham/jax_pep503"
url = "https://jorenham.github.io/jax_pep503/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
