[project]
name = "scratch"
version = "0.1.0"
description = "Deep learning implementations from scratch"
authors = [
    { name = "Nick Wall", email = "46641379+walln@users.noreply.github.com" }
]
dependencies = [
    "numpy>=1.24.4",
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "matplotlib>=3.7.3",
    "scikit-learn>=1.3.1",
    "loguru>=0.7.2",
]
readme = "README.md"
requires-python = ">= 3.11.6"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.1.1",
    "pytest>=7.4.2",
    "pre-commit>=3.5.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
log_cli=true

[tool.ruff]
preview = true
