[tool.poetry]
name = "scratch"
version = "0.1.0"
description = "ML from scratch"
authors = ["Nick <46641379+walln@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"
jaxlib = [
    { version = "^0.4.21", platform = "darwin", source = "pypi" },
    # { extras = [
    #     "cuda12_cudnn89",
    # ], version = "^0.4.21", platform = "linux", source = "jorenham/jax_pep503" },
]
jax = [
    { version = "^0.4.21", platform = "darwin", source = "pypi", extras = [
        "cpu",
    ] },
    # { extras = [
    #     "cuda12_pip",
    # ], version = "^0.4.21", platform = "linux", source = "jorenham/jax_pep503" },
]
# Currently jax-metal only supports jaxlib 0.4.11 - wait for update to support Metal acceleration
# jax-metal = { version = "^0.0.4", platform = "darwin" }
# flax = "^0.7.5"
loguru = "^0.7.2"
matplotlib = "^3.8.2"
scikit-learn = "^1.3.2"
numpy = "^1.26.2"
datasets = "^2.15.0"
optax = "^0.1.7"
tqdm = "^4.66.1"
flax = "^0.7.5"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.7"
pytest = "^7.4.3"
pre-commit = "^3.5.0"

[[tool.poetry.source]]
name = "jorenham/jax_pep503"
url = "https://jorenham.github.io/jax_pep503/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["scratch", "tests"]
pydocstyle.convention = "google"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I",
    # Pydocstyle
    "D",
]

[tool.ruff.lint.isort]
known-first-party = ["scratch"]
