wandb_version: 1

model:
  desc: null
  value:
    num_classes: 10
    input_shape:
    - 28
    - 28
    - 1
trainer:
  desc: null
  value:
    console: <console width=154 ColorSystem.TRUECOLOR>
    checkpoint_path: /home/walln/dev/projects/scratch/checkpoints/nnx-cnn/mnist
    save_checkpoint: false
    resume_checkpoint: false
    epochs: 1
    batch_size: 64
    learning_rate: 0.005
    momentum: 0.9
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719258067
    t:
      1:
      - 1
      - 12
      - 45
      - 49
      - 51
      - 55
      2:
      - 1
      - 12
      - 45
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.12.1
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
