name: CI
on:
    push:
        branches:
        - '**'

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10
          
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Install dependencies
              run: uv sync

            - name: Lint
              run: uvx ruff check --verbose

            - name: Format
              run: uvx ruff format --check

            - name: Typecheck
              run: uvx mypy src --enable-incomplete-feature=NewGenericSyntax

            - name: Test
              run: uv test


