name: CI
on:
    push:
        branches:
        - '**'
    pull_request: 
        branches:
        - '**'
jobs:
    build:
        runs-on: ubuntu-latest
          
        steps:
            - uses: actions/checkout@v4

            - name: Install a specific version
              uses: eifinger/setup-rye@v3
              with:
                version: 'latest'

            - name: Install dependencies
              run: rye sync

            - name: Lint
              run: rye lint

            - name: Format
              run: rye format -- --check

            - name: Test
              run: rye test


